import pytest
import torch as th

from contextlib import nullcontext

from tint.attr import TemporalIntegratedGradients

from tests.basic_models import BasicModel, BasicModel5_MultiArgs


@pytest.mark.parametrize(
    ["forward_func", "multiply_by_inputs", "fails"],
    [
        (BasicModel(), True, False),
        (BasicModel5_MultiArgs(), True, False),
        (BasicModel(), False, False),
    ],
)
def test_init(forward_func, multiply_by_inputs, fails):
    with pytest.raises(Exception) if fails else nullcontext():
        explainer = TemporalIntegratedGradients(forward_func=forward_func, multiply_by_inputs=multiply_by_inputs)
        assert isinstance(explainer, TemporalIntegratedGradients)


@pytest.mark.parametrize(
    [
        "forward_func",
        "multiply_by_inputs",
        "inputs",
        "baselines",
        "target",
        "additional_forward_args",
        "times",
        "n_steps",
        "method",
        "strategy",
        "internal_batch_size",
        "return_convergence_delta",
        "temporal_target",
        "temporal_additional_forward_args",
        "return_temporal_attributions",
        "show_progress",
        "fails",
    ],
    [
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel5_MultiArgs(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            (th.rand(8, 5, 3), th.rand(8, 5, 3)),
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            (True, True),
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            0,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            th.rand(8, 5, 3),
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            0,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            th.Tensor([0, 2, 3, 5, 8, 10]),
            10,
            "gausslegendre",
            "interval",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            -1,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            True,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "riemann_trapezoid",
            "fixed",
            None,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            8,
            False,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            True,
            False,
            None,
            False,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            False,
            False,
            None,
            True,
            False,
            False,
        ),
        (
            BasicModel(),
            True,
            th.rand(8, 5, 3),
            None,
            None,
            None,
            None,
            10,
            "gausslegendre",
            "fixed",
            None,
            True,
            False,
            None,
            False,
            True,
            False,
        ),
    ],
)
def test_time_forward_tunnel(
    forward_func,
    multiply_by_inputs,
    inputs,
    baselines,
    target,
    additional_forward_args,
    times,
    n_steps,
    method,
    strategy,
    internal_batch_size,
    return_convergence_delta,
    temporal_target,
    temporal_additional_forward_args,
    return_temporal_attributions,
    show_progress,
    fails,
):
    with pytest.raises(Exception) if fails else nullcontext():
        explainer = TemporalIntegratedGradients(forward_func=forward_func, multiply_by_inputs=multiply_by_inputs)

        attr = explainer.attribute(
            inputs=inputs,
            baselines=baselines,
            target=target,
            additional_forward_args=additional_forward_args,
            times=times,
            n_steps=n_steps,
            method=method,
            strategy=strategy,
            internal_batch_size=internal_batch_size,
            return_convergence_delta=return_convergence_delta,
            temporal_target=temporal_target,
            temporal_additional_forward_args=temporal_additional_forward_args,
            return_temporal_attributions=return_temporal_attributions,
            show_progress=show_progress,
        )

        if return_convergence_delta:
            attr, delta = attr
            assert tuple(delta.shape) == (40,)

        if return_temporal_attributions:
            assert tuple(attr.shape) == (inputs.shape[0], inputs.shape[1]) + inputs.shape[1:]
        else:
            assert attr.shape == inputs.shape
