name: Build LaTeX document

on:
  push:
    paths:
      - docs/paper/**

jobs:
  build_latex:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: docs/paper

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: docs/paper/main.pdf