name: Tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # Install package
          pip install .

      - name: Pytest
        run: |
          # Install tests packages
          pip install -r tests/requirements.txt
          # Perform the tests
          pytest --cov-report term-missing --cov-report=xml --cov=tint tests/ --cov-config=tests/.coveragerc